### ISSUE TITLE
We need a new name!

### ISSUE THREAD

**Issue by bkrahmer** [Sixt/ja-micro#2]
Oracle has requested we not use 'java' in the name.  micro-j and j-micro are already in use by companies.  We need a catchy name.  Please help!

**Comment by alexborlis** [comment]
I suggest smth not technical but more human lang and it must describe point
of architecture. Unfortunately "ant" is already taken also:)

**Comment by asim** [comment]
My suggestion is **ja-micro**. Stays consistent with the 2 letter prefix.

**Comment by ferrantim** [comment]
I guess the good news is that people are taking notice :)

**Comment by asim** [comment]
When Oracle comes knocking you know you're on to something :)

**Comment by JonathanWolfe** [comment]
`Banam`, `Bitty` (of itsy-bitsy spider fame), or `Runt`

**Comment by ItsT-Mo** [comment]
Maybe something like

µJay

(pronounced MicroJay)

**Comment by ItsT-Mo** [comment]
Never mind I overread the part that Micro-Jay is taken

**Comment by tomdkt** [comment]
Microwave

**Comment by ericqweinstein** [comment]
What about Espresso?

**Comment by abde55amad** [comment]
Microbe

**Comment by abde55amad** [comment]
Microbe, includes the word Micro, and symbolizes something small and dynamic, and that can be easily multiplied (like microservice instances)

**Comment by antoabrand** [comment]
How about, Jamaica, as in spanish for Hibiscus tea.  It would need the i with the accent. Pronounced Ha-mic-uh

**Comment by alexborlis** [comment]
+1 for microbe

**Comment by tomasulo** [comment]
How about just j-micro ?

**Comment by madamiak** [comment]
+1 for Espresso, as it is 'micro' coffee and you already know Java-coffee correlation .

**Comment by manolovl** [comment]
@ericqweinstein @madamiak, sounds kind of cool, but then you might have Google after you, instead of Oracle [Espresso Framework](https://google.github.io/android-testing-support-library/docs/espresso/)

**Comment by gnomix** [comment]
how about microscope?

**Comment by raderio** [comment]
JMLF - Java micro lightweight framework

**Comment by michalgor** [comment]
Microbean ?
Microffee ?

**Comment by ericqweinstein** [comment]
@manolovl, good point about the Android Espresso framework. Are there any good spelling/typographical changes we could make to distinguish, or is that just asking for more confusion?

**Comment by abde55amad** [comment]
A microbe is a microscopic living organism, which may be single-celled or multicellular(just like Microsevice instances).
Microbes can propagate easily(scalability), very small and compact (that's the definition of microservices in general).and the most important, Lightweight :P, the particularity of this framework.

**Comment by boyand** [comment]
ja-micro it is. Thanks for all the creative suggestions!
