### ISSUE TITLE
Still contributing ?

### ISSUE THREAD

**Issue by jeveloper** [Sixt/ja-micro#58]
Hi there, just curious what happened.

It seemed that there were regular contributions

Thank you

**Comment by bkrahmer** [comment]
Hi Serge,
  ja-micro was (from our standpoint) pretty well feature-complete when it was released as an open-source project.  We've had services using it in production for over a year now.  There are still some features that I would like to add, but not much that is blocking us from our normal development cycle.  I don't have a good feel for how many other people are using ja-micro, but if there are any, I guess they are pretty satisfied with the feature-set, quality and performance :)
  Please let me know if you are using it.

cheers,
brian

**Comment by jeveloper** [comment]
Thanks for your response.

I've taken a position , to observe a library and its history of changes, improvements. I'm sure you can relate. 

I will plan to evaluate ja-micro in the next few months with one project and possible use it further.

**Comment by bkrahmer** [comment]
Ok, great.  Looking forward to your feedback.
