### ISSUE TITLE
Add support for consul version 1.x.x

### ISSUE THREAD

**Issue by andysabitov** [Sixt/ja-micro#61]
Consul 1.0.0 has breaking API changes, see [CHANGELOG](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#100-october-16-2017) and [PR](https://github.com/hashicorp/consul/pull/3405)

Starting from this release it's not possible to use GET to update health checks. While trying do it we're getting: "Received 405 trying to update health".

It is necessary to use PUT verb for updating health checks.

**Comment by codec** [comment]
fixed w/ #62
