### ISSUE TITLE
missing com.google.*; packages

### ISSUE THREAD

**Issue by gerryDreamer** [Sixt/ja-micro#8]
please include all packages, especially google ones

**Comment by bkrahmer** [comment]
It's not clear what you are requesting...

**Comment by zbhuang** [comment]
I guess gerryDreamer ran into the same issue as I had before.
gerryDreamer, please check out the issue I just closed about "compilation issue".
If you import the projects into java IDE (say IntelliJ), then it should automatically download those dependent jar files to your local machine.

**Comment by gerryDreamer** [comment]
i'm using NetBeans, but let me try, thanks.

**Comment by bkrahmer** [comment]
I believe it was an incorrect usage, so I'm going to close now.  BTW, artifacts are now available, so no need to download and build source.  See the wiki.  Better getting started docs and videos coming soon!
